#==========================  Modules configuration ============================
metricbeat.modules:

#------------------------------- Docker Module -------------------------------
- module: mongodb
  metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
  hosts: ["hub-mongo.local:27017", "admin-mongo.local:27017"]
  enabled: true
  period: 10s

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "image", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

- module: rabbitmq
  metricsets:
    - node
    - queue
    - connection
  period: 10s
  hosts: ["rabbitmq.local:15672"]
  enabled: true
  username: root
  password: local-dev

- module: elasticsearch
  metricsets:
   - node
   - node_stats
  period: 10s
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "local-dev"

# - module: postgresql
#   metricsets:
#    - database
#    - bgwriter
#    - activity
#   period: 10s
#   hosts: ["postgres://localhost:5432"]
  #username: user
  #password: pass

- module: kibana
  metricsets:
   - status
  period: 10s
  hosts: ["kibana:5601"]
  #basepath: ""
  #username: "user"
  #password: "secret"

- module: logstash
  metricsets:
   - node
   - node_stats
  period: 10s
  hosts: ["logstash:9600"]
  #username: "user"
  #password: "secret"

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  password: local-dev

setup.kibana.host: 'kibana:5601'
