version: "3.7"

networks:
  elk-net:
    driver: bridge

services:
  elasticsearch:
    container_name: $ES_CONTAINER_NAME
    hostname: $ES_CONTAINER_NAME
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk-net
